const assert = require("node:assert/strict");
const path = require("node:path");
const { pathToFileURL } = require("node:url");
const { chromium } = require("playwright");
(async () => {
  const browser = await chromium.launch({ channel: "msedge", headless: true });
  try {
    const page = await browser.newPage({ viewport: { width: 1440, height: 960 } });
    const errors = [];
    page.on("pageerror", e => errors.push(e.message));
    await page.clock.install();
    await page.goto(pathToFileURL(path.resolve(__dirname, "../peripheral-vision-trainer.html")).href);
    await page.locator("#ackSafetyBtn").click();
    await page.locator("#cursorPanelBtn").click();
    await page.locator('[data-cursor-style="ring"]').click();
    await page.locator("#cursorPanelClose").click();
    await page.locator("#multitaskFiveBtn").click();
    await page.locator("#startBtn").click();
    await page.clock.pauseAt(new Date(Date.now()+1000));
    assert.equal(await page.locator("#multiIntro").isVisible(),true);
    const pausedScore=await page.evaluate(()=>multi.elapsed);
    await page.keyboard.press("Space");
    await page.clock.runFor(1000);
    assert.equal(await page.evaluate(()=>multi.elapsed),pausedScore);
    await page.locator("#multiContinue").click();
    assert.equal(await page.locator("#multitaskLayer").isVisible(), true);
    const board = await page.locator("#multiCanvas").boundingBox();
    const overlay = await page.locator("#multiTargets").boundingBox();
    assert.ok(board.x > 100 && board.y > 64, "gameplay leaves margins");
    assert.ok(board.width <= 1100 && board.height <= 720);
    assert.deepEqual(overlay,board,"DOM targets and canvas share centered bounds");
    await page.mouse.click(20,160);
    assert.equal(await page.evaluate(()=>multi.running),true,"margin clicks are ignored");
    await page.mouse.move(300,220);
    assert.equal(await page.locator("#cursorAim").count(),1);
    assert.equal(await page.locator("#multitaskLayer #cursorAim.ring.show").count(),1);
    assert.equal(await page.locator("#multiCanvas").evaluate(el=>getComputedStyle(el).cursor),"none");
    assert.equal(await page.locator("#multiExit").evaluate(el=>getComputedStyle(el).cursor),"none");
    assert.equal(await page.locator("#cursorAim").evaluate(el=>el.style.getPropertyValue("--cursor-x")),"300px");
    assert.equal(await page.locator("#cursorAim").evaluate(el=>getComputedStyle(el).pointerEvents),"none");
    const targetsBeforeMiss = await page.evaluate(() => multi.targets.map(t => ({hp:t.hp,due:t.due})));
    const emptyPoint = await page.evaluate(() => {
      const a=multiArea(0),r=multiCanvas.getBoundingClientRect();
      return {x:r.left+a.x+2,y:r.top+a.y+2};
    });
    await page.mouse.click(emptyPoint.x,emptyPoint.y);
    await page.mouse.click(emptyPoint.x,emptyPoint.y);
    assert.equal(await page.evaluate(() => multi.running), true, "empty clicks do not end the run");
    assert.deepEqual(await page.evaluate(() => multi.targets.map(t => ({hp:t.hp,due:t.due}))), targetsBeforeMiss);
    assert.equal(await page.locator("#multiTargets .target").count(), 3);
    assert.equal(await page.evaluate(()=>multiTargetRadius(multiArea(0))),58);
    const edge = await page.evaluate(()=>{
      const a=multiArea(0),t=multi.targets[1],r=multiCanvas.getBoundingClientRect();
      return {x:r.left+a.x+t.x*a.w+52,y:r.top+a.y+t.y*a.h};
    });
    await page.mouse.click(edge.x,edge.y);
    assert.equal(await page.evaluate(()=>multi.targets[1].hp),1,"enlarged outer area accepts hits");
    await page.mouse.click(edge.x,edge.y);
    await page.clock.runFor(450);
    assert.match(await page.locator("#multiTargets .target").first().evaluate(el=>getComputedStyle(el).backgroundImage), /radial-gradient/);
    assert.notEqual(await page.locator("#multiTargets .target").first().evaluate(el=>getComputedStyle(el).boxShadow), "none");
    const clickTarget = async () => {
      const p = await page.evaluate(() => {
        const a=multiArea(0),t=multi.targets[0],r=multiCanvas.getBoundingClientRect();
        return {x:r.left+a.x+t.x*a.w,y:r.top+a.y+t.y*a.h};
      });
      await page.mouse.click(p.x,p.y);
    };
    await clickTarget();
    assert.equal(await page.locator("#multiTargets .hit-burst").count(), 1);
    assert.equal(await page.evaluate(() => multi.targets[0].hp), 1);
    await clickTarget();
    assert.deepEqual(await page.evaluate(() => multi.targets.map(t=>t.hp)), [2,2,2]);
    // Fixture isolates boundary transitions from the independent task deadlines.
    const phase = async seconds => {
      await page.evaluate(seconds => {
      multi.elapsed=seconds-.01;
      multi.targets.forEach(t=>t.due=seconds+10);
      if(multi.hold)multi.hold.due=seconds+8;
      multi.shots=[];
      multi.float={y:.45,vy:0};
      multi.flightObstacles=[];
      multi.nextFlight=seconds+2;
      multiStep(.02); multiDraw();
      }, seconds);
      if(await page.locator("#multiIntro").isVisible()) {
        const elapsed=await page.evaluate(()=>multi.elapsed);
        await page.clock.runFor(500);
        assert.equal(await page.evaluate(()=>multi.elapsed),elapsed,"new task explanation pauses the run");
        await page.screenshot({path:path.resolve(__dirname,"../../../work/multitask-intro.png")});
        await page.locator("#multiContinue").click();
      }
      await page.clock.runFor(17);
    };
    await phase(10);
    assert.equal(await page.evaluate(()=>multi.phase),2);
    const x=await page.evaluate(()=>multi.player.x);
    await page.keyboard.down("d");
    await page.clock.runFor(200);
    await page.keyboard.up("d");
    assert.equal(await page.evaluate(()=>multi.player.x),x);
    const y=await page.evaluate(()=>multi.player.y);
    await page.keyboard.down("w");
    await page.clock.runFor(200);
    await page.keyboard.up("w");
    assert.ok(await page.evaluate(()=>multi.player.y)<y);
    await phase(20);
    assert.equal(await page.evaluate(()=>multi.phase),3);
    const hx=await page.evaluate(()=>multi.hold.x);
    await page.keyboard.down("a");
    await page.clock.runFor(200);
    await page.keyboard.up("a");
    assert.ok(await page.evaluate(()=>multi.hold.x)<hx);
    await page.evaluate(()=>{multi.hold.x=multi.hold.goal;multiStep(.5);});
    assert.ok(await page.evaluate(()=>multi.hold.time)>=.5);
    await page.evaluate(()=>{multi.hold.x=.5;multiStep(.01);});
    assert.equal(await page.evaluate(()=>multi.hold.time),0);
    const goal=await page.evaluate(()=>multi.hold.goal);
    await page.evaluate(()=>{multi.hold.x=multi.hold.goal;multiStep(.5);multiStep(.51);});
    assert.notEqual(await page.evaluate(()=>multi.hold.goal),goal);
    await phase(30);
    assert.equal(await page.evaluate(()=>multi.phase),4);
    await page.keyboard.down("Space");
    await page.clock.runFor(200);
    assert.ok(await page.evaluate(()=>multi.float.vy)<0);
    assert.ok(await page.evaluate(()=>multi.float.vy)>=-.22,"gentle ascent is speed limited");
    await page.keyboard.up("Space");
    await page.clock.runFor(300);
    assert.ok(await page.evaluate(()=>multi.float.vy)>0, "release descends");
    assert.ok(await page.evaluate(()=>multi.float.vy)<=.12,"release descends slowly");
    await page.evaluate(()=>{multi.nextFlight=multi.elapsed;multiStep(.001);});
    assert.ok(await page.evaluate(()=>multi.flightObstacles.every(o=>o.h>=.2&&o.h<=.32)));
    assert.ok(await page.evaluate(()=>multi.nextFlight-multi.elapsed)>=4.99);
    await page.evaluate(()=>multi.hold.due=100);
    await phase(40);
    assert.equal(await page.evaluate(()=>multi.phase),5);
    assert.equal(await page.evaluate(()=>multiRects().length),5);
    const panes = await page.evaluate(()=>multiRects());
    assert.equal(panes[0].x,panes[1].x);
    assert.equal(panes[2].x,panes[3].x);
    assert.ok(panes[1].y>panes[0].y && panes[3].y>panes[2].y);
    assert.ok(panes[2].x>panes[0].x && panes[4].x>panes[2].x);
    const mapPoint=await page.evaluate(()=>{
      const a=multiMapArea(),r=multiCanvas.getBoundingClientRect();
      const p=multi.lane==="TOP"?[.4,.12]:multi.lane==="BOT"?[.6,.88]:[.5,.5];
      return {x:r.left+a.x+a.w*p[0],y:r.top+a.y+a.h*p[1]};
    });
    await page.mouse.click(mapPoint.x,mapPoint.y);
    assert.equal(await page.evaluate(()=>multi.lane),"");
    assert.equal(await page.evaluate(()=>multi.running),true);
    await page.screenshot({path:path.resolve(__dirname,"../../../work/multitask-desktop.png")});
    assert.ok(await page.evaluate(()=> {
      const data=multiCtx.getImageData(0,0,multiCanvas.width,multiCanvas.height).data;
      let bright=0;for(let i=0;i<data.length;i+=4)if(data[i]>100)bright++;
      return bright>1000;
    }),"canvas contains visible gameplay");
    await page.setViewportSize({width:600,height:900});
    await page.screenshot({path:path.resolve(__dirname,"../../../work/multitask-small.png")});
    await page.evaluate(()=>{multi.lane="MID";multi.laneDue=multi.elapsed+.01;multiStep(.02);});
    assert.match(await page.locator("#multiReason").innerText(),/時間切れ/);
    assert.match(await page.locator("#multiFinal").innerText(),/40/);
    const finalScore=await page.locator("#multiFinal").innerText();
    await page.locator("#multiRetry").focus();
    for(const key of ["Space","Enter","w","a","s","d","Escape"]) await page.keyboard.press(key);
    await page.clock.runFor(1200);
    assert.equal(await page.evaluate(()=>multi.running),false,"gameplay keys cannot restart after game over");
    assert.equal(await page.locator("#multiResult").isVisible(),true);
    assert.equal(await page.locator("#multiFinal").innerText(),finalScore,"final score remains visible and unchanged");
    assert.match(await page.locator("#multiBest").innerText(),/BEST/);
    await page.locator("#multiRetry").click();
    assert.equal(await page.evaluate(()=>multi.phase),1);
    await page.evaluate(()=>{multi.targets[0].due=multi.elapsed;multiStep(.01);});
    assert.match(await page.locator("#multiReason").innerText(),/TARGET/);
    await page.locator("#multiRetry").click();
    await phase(10);
    await page.evaluate(()=>{multi.shots=[{x:multi.player.x,y:multi.player.y,fire:0}];multiStep(.001);});
    assert.match(await page.locator("#multiReason").innerText(),/被弾/);
    await page.locator("#multiRetry").click();
    await phase(20);
    await page.evaluate(()=>{multi.hold.due=multi.elapsed;multiStep(.001);});
    assert.match(await page.locator("#multiReason").innerText(),/HOLD/);
    await page.locator("#multiRetry").click();
    await phase(30);
    await page.evaluate(()=>{multi.float.y=.95;multiStep(.001);});
    assert.equal(await page.evaluate(()=>multi.running),true,"floor is safe");
    assert.equal(await page.evaluate(()=>multi.float.y),.94);
    await page.evaluate(()=>{multi.float.y=-.01;multiStep(.001);});
    assert.equal(await page.evaluate(()=>multi.running),true,"ceiling is safe");
    await page.evaluate(()=>{multi.flightObstacles=[{x:.33,w:.075,h:1,bottom:true}];multiStep(.001);});
    assert.match(await page.locator("#multiReason").innerText(),/障害物/);
    await page.locator("#multiRetry").click();
    await phase(40);
    await page.evaluate(()=>{multi.lane="TOP";multiDraw();});
    const wrong=await page.evaluate(()=>{const a=multiMapArea(),r=multiCanvas.getBoundingClientRect();return{x:r.left+a.x+a.w*.5,y:r.top+a.y+a.h*.88};});
    await page.mouse.click(wrong.x,wrong.y);
    assert.match(await page.locator("#multiReason").innerText(),/違うレーン/);
    await page.locator("#multiMenu").click();
    assert.equal(await page.locator("#multitaskLayer").isVisible(),false);
    assert.equal(await page.locator("#stage #cursorAim.ring").count(),1);
    assert.equal(await page.locator("#cursorAim").count(),1);
    assert.equal(await page.locator("#multiTargets .target").count(),0);
    await page.locator("#multitaskBtn").click();
    assert.equal(await page.locator("#multitaskFiveBtn").getAttribute("aria-pressed"),"false");
    await page.locator("#startBtn").click();
    await phase(40);
    assert.equal(await page.evaluate(()=>multi.phase),4);
    assert.equal(await page.evaluate(()=>multiRects().length),4);
    assert.equal(await page.evaluate(()=>multi.lane),"");
    await phase(100);
    assert.equal(await page.evaluate(()=>multi.phase),4,"four-task mode never adds a fifth task");
    await page.evaluate(()=>endMultitask("TEST"));
    assert.ok(await page.evaluate(()=>Number(localStorage.getItem("eyesforge-multitask-4-best-v1")))>=100);
    await page.locator("#multiRetry").click();
    assert.equal(await page.evaluate(()=>multi.maxTasks),4);
    await page.locator("#multiExit").click();
    assert.deepEqual(errors,[]);
    console.log("PASS: five stages, WS/AD isolation, continuous hold/reset/timeout, Space, lanes, failures, retry, menu, rendering.");
  } finally { await browser.close(); }
})().catch(e=>{console.error(e);process.exitCode=1;});
